- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=unix:///var/run/crio/crio.sock
  register: init_output

- name: Configure kubectl for root user
  shell: |
    mkdir -p /root/.kube
    cp -i /etc/kubernetes/admin.conf /root/.kube/config
    chown $(id -u root):$(id -g root) /root/.kube/config

- name: Install Pod Network
  become: yes
  shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

- name: Retrieve Join Command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set Join Command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
